// app/app/profile/addresses.tsx
import { useCallback, useEffect, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'

import { api, ApiError, type Address } from '@/lib/api'
import { useCatalogue } from '@/lib/catalogue'
import { pick, t, useLang } from '@/lib/i18n'
import { AppBar, Body, Button, Empty, Field, Loading, Note, Small, inputStyle } from '@/components/ui'
import { color, font, space } from '@/theme/tokens'

type Draft = {
  id: string | null
  label: string
  line: string
  notes: string
  delivery_zone_id: string
}

export default function Addresses () {
  const catalogue = useCatalogue()
  useLang()

  const [addresses, setAddresses] = useState<Address[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [draft, setDraft] = useState<Draft | null>(null)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const { data } = await api.addresses()
      setAddresses(data)
    } catch (e) {
      setError((e as ApiError).isOffline ? t('err.offline') : t('err.generic'))
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load() }, [load])

  function startNew () {
    setDraft({
      id: null, label: '', line: '', notes: '',
      delivery_zone_id: catalogue.zones[0]?.id ?? '',
    })
  }

  function startEdit (a: Address) {
    setDraft({
      id: a.id,
      label: a.label ?? '',
      line: a.line,
      notes: a.notes ?? '',
      delivery_zone_id: a.delivery_zone_id ?? catalogue.zones[0]?.id ?? '',
    })
  }

  async function save () {
    if (!draft || !draft.line.trim() || !draft.delivery_zone_id) return
    setSaving(true); setError(null)

    const body = {
      label: draft.label.trim() || null,
      line: draft.line.trim(),
      notes: draft.notes.trim() || null,
      delivery_zone_id: draft.delivery_zone_id,
    }

    try {
      if (draft.id) await api.updateAddress(draft.id, body)
      else await api.createAddress(body)
      setDraft(null)
      await load()
    } catch (e) {
      setError(Object.values((e as ApiError).fieldErrors)[0] ?? t('err.generic'))
    } finally {
      setSaving(false)
    }
  }

  async function remove (id: string) {
    try { await api.deleteAddress(id); await load() }
    catch (e) { setError((e as ApiError).message ?? t('err.generic')) }
  }

  if (loading) return <View style={{ flex: 1 }}><AppBar title={t('profile.addresses')} back /><Loading /></View>

  if (draft) {
    return (
      <View style={{ flex: 1 }}>
        <AppBar title={t('address.title')} back />
        <ScrollView contentContainerStyle={{ padding: space.gutter, paddingBottom: 36 }}>
          <Field label={t('address.label')}>
            <TextInput style={inputStyle} value={draft.label} maxLength={40}
              onChangeText={(v) => setDraft({ ...draft, label: v })} />
          </Field>

          <Field label={t('address.line')}>
            <TextInput style={inputStyle} value={draft.line} maxLength={300}
              autoComplete="street-address" textContentType="fullStreetAddress"
              onChangeText={(v) => setDraft({ ...draft, line: v })} />
          </Field>

          <Field label={t('address.notes')}>
            <TextInput style={inputStyle} value={draft.notes} maxLength={200}
              onChangeText={(v) => setDraft({ ...draft, notes: v })} />
          </Field>

          <Field label={t('address.zone')} error={error}>
            <View style={{ gap: 10 }}>
              {catalogue.zones.map(z => (
                <Pressable
                  key={z.id}
                  onPress={() => setDraft({ ...draft, delivery_zone_id: z.id })}
                  accessibilityRole="radio"
                  accessibilityState={{ selected: draft.delivery_zone_id === z.id }}
                  style={[s.option, draft.delivery_zone_id === z.id && s.optionOn]}
                >
                  <View style={[s.dot, draft.delivery_zone_id === z.id && s.dotOn]} />
                  <Body>{pick(z.name)}</Body>
                </Pressable>
              ))}
            </View>
          </Field>

          <Button title={t('address.save')} onPress={save} busy={saving} disabled={!draft.line.trim()} />
          <Button title={t('cancel')} variant="ghost" onPress={() => setDraft(null)} style={{ marginTop: 10 }} />
        </ScrollView>
      </View>
    )
  }

  return (
    <View style={{ flex: 1 }}>
      <AppBar title={t('profile.addresses')} back />
      <ScrollView contentContainerStyle={{ padding: space.gutter, paddingBottom: 36 }}>
        {error ? <View style={{ marginBottom: 14 }}><Note warn>{error}</Note></View> : null}

        {addresses.length === 0 ? (
          <Empty title={t('address.none')} />
        ) : addresses.map(a => (
          <View key={a.id} style={s.card}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
              {a.label ? <Text style={s.cardLabel}>{a.label}</Text> : null}
              {a.is_default ? <View style={s.badge}><Text style={s.badgeText}>✓</Text></View> : null}
            </View>
            <Body>{a.line}</Body>
            {a.notes ? <Small muted>{a.notes}</Small> : null}

            <View style={s.actions}>
              <Pressable onPress={() => startEdit(a)}><Text style={s.action}>{t('address.save')}</Text></Pressable>
              <Pressable onPress={() => remove(a.id)}>
                <Text style={[s.action, { color: color.brick }]}>{t('address.delete')}</Text>
              </Pressable>
            </View>
          </View>
        ))}

        <Button title={t('checkout.addAddress')} onPress={startNew} style={{ marginTop: 8 }} />
      </ScrollView>
    </View>
  )
}

const s = StyleSheet.create({
  card: {
    backgroundColor: '#fff', borderRadius: space.radius,
    borderWidth: StyleSheet.hairlineWidth, borderColor: color.lineSoft,
    padding: 15, marginBottom: 11, gap: 2,
  },
  cardLabel: { fontFamily: font.semi, fontSize: 16, color: color.ink },
  badge: { backgroundColor: color.leafXl, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2 },
  badgeText: { fontFamily: font.semi, fontSize: 11, color: color.forest2 },
  actions: { flexDirection: 'row', gap: 18, marginTop: 12 },
  action: { fontFamily: font.semi, fontSize: 14, color: color.forest, textDecorationLine: 'underline' },
  option: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: '#fff', borderWidth: 1, borderColor: color.line,
    borderRadius: space.radius, padding: 14,
  },
  optionOn: { borderColor: color.forest, borderWidth: 2 },
  dot: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: color.line },
  dotOn: { borderColor: color.forest, borderWidth: 6 },
})

// app/src/views/Addresses.vue
<script setup>
import { ref, onMounted } from 'vue'
import { api } from '../api/client'
import { useCatalogue } from '../stores/catalogue'
import AppBar from '../components/AppBar.vue'
import { t, pick } from '../i18n'

const catalogue = useCatalogue()

const addresses = ref([])
const loading = ref(true)
const error = ref('')
const saving = ref(false)

const editing = ref(null)   // null = list, otherwise the form model

onMounted(load)

async function load () {
  loading.value = true
  try {
    const { data } = await api.addresses()
    addresses.value = data
  } catch (e) {
    error.value = e.status === 0 ? t('err.offline') : t('err.generic')
  } finally {
    loading.value = false
  }
}

function startNew () {
  editing.value = {
    id: null,
    label: '',
    line: '',
    notes: '',
    delivery_zone_id: catalogue.zones[0]?.id ?? '',
    is_default: addresses.value.length === 0,
  }
}

function startEdit (a) {
  editing.value = { ...a, label: a.label ?? '', notes: a.notes ?? '' }
}

async function save () {
  const form = editing.value
  if (!form.line.trim() || !form.delivery_zone_id) return

  saving.value = true
  error.value = ''

  const body = {
    label: form.label.trim() || null,
    line: form.line.trim(),
    notes: form.notes.trim() || null,
    delivery_zone_id: form.delivery_zone_id,
    is_default: form.is_default,
  }

  try {
    if (form.id) await api.updateAddress(form.id, body)
    else await api.createAddress(body)
    editing.value = null
    await load()
  } catch (e) {
    error.value = Object.values(e.fieldErrors ?? {})[0] ?? t('err.generic')
  } finally {
    saving.value = false
  }
}

async function remove (id) {
  try {
    await api.deleteAddress(id)
    await load()
  } catch (e) {
    error.value = e.message ?? t('err.generic')
  }
}
</script>

<template>
  <main class="screen">
    <AppBar :title="t('profile.addresses')" back />

    <div v-if="loading" class="empty"><span class="spinner" style="margin:0 auto" /></div>

    <template v-else-if="editing">
      <section class="wrap addr__section">
        <label class="field">
          <span class="field__label">{{ t('address.label') }}</span>
          <input v-model="editing.label" class="field__input" type="text" maxlength="40">
        </label>

        <label class="field">
          <span class="field__label">{{ t('address.line') }}</span>
          <input v-model="editing.line" class="field__input" type="text" maxlength="300" autocomplete="street-address">
        </label>

        <label class="field">
          <span class="field__label">{{ t('address.notes') }}</span>
          <input v-model="editing.notes" class="field__input" type="text" maxlength="200">
        </label>

        <label class="field">
          <span class="field__label">{{ t('address.zone') }}</span>
          <select v-model="editing.delivery_zone_id" class="field__input">
            <option v-for="z in catalogue.zones" :key="z.id" :value="z.id">{{ pick(z.name) }}</option>
          </select>
        </label>

        <p v-if="error" class="field__error">{{ error }}</p>

        <button class="btn btn--primary btn--block" :disabled="saving || !editing.line.trim()" @click="save">
          <span v-if="saving" class="spinner" /> {{ t('address.save') }}
        </button>
        <button class="btn btn--ghost btn--block" style="margin-top:10px" @click="editing = null">
          {{ t('cancel') }}
        </button>
      </section>
    </template>

    <template v-else>
      <div v-if="!addresses.length" class="empty">
        <h3>{{ t('address.none') }}</h3>
      </div>

      <section v-else class="wrap addr__section">
        <article v-for="a in addresses" :key="a.id" class="addr">
          <div class="addr__body">
            <strong v-if="a.label">{{ a.label }}</strong>
            <span v-if="a.is_default" class="pill pill--done addr__default">✓</span>
            <p>{{ a.line }}</p>
            <p v-if="a.notes" class="small muted">{{ a.notes }}</p>
          </div>
          <div class="addr__actions">
            <button @click="startEdit(a)">{{ t('address.save') }}</button>
            <button class="addr__del" @click="remove(a.id)">{{ t('address.delete') }}</button>
          </div>
        </article>
      </section>

      <div class="wrap addr__section">
        <button class="btn btn--primary btn--block" @click="startNew">
          {{ t('checkout.addAddress') }}
        </button>
      </div>
    </template>
  </main>
</template>

<style scoped>
.addr__section{ padding-top:18px; }
.addr{
  padding:15px;
  background:#fff; border:1px solid var(--line-soft); border-radius:var(--radius);
  margin-bottom:11px;
}
.addr__default{ margin-left:8px; }
.addr__actions{ display:flex; gap:16px; margin-top:12px; }
.addr__actions button{
  font-size:.86rem; font-weight:600; color:var(--forest);
  text-decoration:underline; text-underline-offset:3px;
}
.addr__del{ color:var(--brick) !important; }
</style>
