// app/app/checkout.tsx
import { useCallback, useEffect, useState } from 'react'
import { Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'

import { api, ApiError, type Address } from '@/lib/api'
import { useCart } from '@/lib/cart'
import { useCatalogue } from '@/lib/catalogue'
import { useAuth } from '@/lib/auth'
import { t, useLang } from '@/lib/i18n'
import { money } from '@/lib/money'
import { AppBar, Body, Button, Field, Loading, Note, Row, Small, inputStyle } from '@/components/ui'
import { color, font, space } from '@/theme/tokens'

export default function Checkout () {
  const cart = useCart()
  const catalogue = useCatalogue()
  const auth = useAuth()
  const router = useRouter()
  useLang()

  const [addresses, setAddresses] = useState<Address[]>([])
  const [addressId, setAddressId] = useState<string | null>(null)
  const [date, setDate] = useState('')
  const [payment, setPayment] = useState<'cash' | 'pos'>('cash')
  const [note, setNote] = useState('')
  const [loading, setLoading] = useState(true)
  const [placing, setPlacing] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const lead = catalogue.delivery?.lead_days ?? 1
  const minDate = isoDaysFromNow(lead)
  const maxDate = isoDaysFromNow(14)

  const load = useCallback(async () => {
    try {
      const { data } = await api.addresses()
      setAddresses(data)

      const chosen = data.find(a => a.is_default) ?? data[0]
      if (chosen) {
        setAddressId(chosen.id)
        // The delivery fee depends on the zone, so the basket is re-priced now
        // that one is known — it was quoted without a zone.
        cart.setZone(chosen.delivery_zone_id)
      }
      setDate(minDate)
    } catch (e) {
      setError((e as ApiError).isOffline ? t('err.offline') : t('err.generic'))
    } finally {
      setLoading(false)
    }
    // cart.setZone is stable; re-running on every cart change would refetch
    // addresses on every quantity tap.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [minDate])

  useEffect(() => { load() }, [load])

  function pickAddress (a: Address) {
    setAddressId(a.id)
    cart.setZone(a.delivery_zone_id)
  }

  const quote = cart.quote
  const canPlace = Boolean(addressId) && Boolean(date) && auth.profileComplete &&
    Boolean(quote?.meets_minimum) && !placing

  async function place () {
    if (!canPlace) return
    setPlacing(true); setError(null)

    try {
      // Ids and quantities only. No prices leave this device.
      const order = await api.placeOrder({
        address_id: addressId,
        delivery_date: date,
        payment_method: payment,
        note: note.trim() || undefined,
        lines: cart.lines,
      })

      await cart.clear()
      router.replace({ pathname: '/orders/[id]', params: { id: order.id, placed: '1' } })
    } catch (e) {
      const err = e as ApiError
      const unavailable = err.payload?.unavailable_product_ids as string[] | undefined

      if (unavailable?.length) {
        await cart.dropUnavailable(unavailable)
        setError(err.message)
      } else {
        setError(Object.values(err.fieldErrors)[0] ?? err.message ?? t('err.generic'))
      }
    } finally {
      setPlacing(false)
    }
  }

  if (loading) return <View style={{ flex: 1 }}><AppBar title={t('checkout.title')} back /><Loading /></View>

  return (
    <View style={{ flex: 1 }}>
      <AppBar title={t('checkout.title')} back />

      <ScrollView contentContainerStyle={{ padding: space.gutter, paddingBottom: 36 }}>
        {/* A courier cannot deliver to a customer with no name and no phone.
            The server refuses the order too, so this is a shortcut rather than
            the control. */}
        {!auth.profileComplete ? (
          <View style={{ marginBottom: 22 }}>
            <Note warn>{t('profile.complete')}</Note>
            <Button
              title={t('profile.title')}
              variant="ghost"
              onPress={() => router.push('/(tabs)/profile')}
              style={{ marginTop: 12 }}
            />
          </View>
        ) : null}

        <Text style={s.heading}>{t('checkout.address')}</Text>

        {addresses.length ? addresses.map(a => (
          <Pressable
            key={a.id}
            onPress={() => pickAddress(a)}
            accessibilityRole="radio"
            accessibilityState={{ selected: addressId === a.id }}
            style={[s.option, addressId === a.id && s.optionOn]}
          >
            <View style={[s.dot, addressId === a.id && s.dotOn]} />
            <View style={{ flex: 1 }}>
              {a.label ? <Text style={s.optionTitle}>{a.label}</Text> : null}
              <Body>{a.line}</Body>
              {a.notes ? <Small muted>{a.notes}</Small> : null}
            </View>
          </Pressable>
        )) : <Small muted>{t('address.none')}</Small>}

        <Button
          title={t('checkout.addAddress')}
          variant="ghost"
          onPress={() => router.push('/profile/addresses')}
          style={{ marginTop: 12 }}
        />

        <Text style={[s.heading, { marginTop: 26 }]}>{t('checkout.date')}</Text>
        <Field hint={t('checkout.dateNote')}>
          <TextInput
            style={inputStyle}
            value={date}
            onChangeText={setDate}
            placeholder={minDate}
            placeholderTextColor={color.ink3}
            keyboardType={Platform.OS === 'ios' ? 'numbers-and-punctuation' : 'default'}
            autoCapitalize="none"
            autoCorrect={false}
            maxLength={10}
          />
        </Field>
        <Small muted style={{ marginTop: -8 }}>{minDate} — {maxDate}</Small>

        <Text style={[s.heading, { marginTop: 26 }]}>{t('checkout.payment')}</Text>
        {(['cash', 'pos'] as const).map(method => (
          <Pressable
            key={method}
            onPress={() => setPayment(method)}
            accessibilityRole="radio"
            accessibilityState={{ selected: payment === method }}
            style={[s.option, payment === method && s.optionOn]}
          >
            <View style={[s.dot, payment === method && s.dotOn]} />
            <Text style={s.optionTitle}>
              {method === 'cash' ? t('checkout.cash') : t('checkout.pos')}
            </Text>
          </Pressable>
        ))}
        <Small muted style={{ marginTop: 8 }}>{t('checkout.paymentNote')}</Small>

        <View style={{ marginTop: 26 }}>
          <Field label={t('checkout.note')}>
            <TextInput
              style={[inputStyle, { minHeight: 80, textAlignVertical: 'top' }]}
              value={note}
              onChangeText={setNote}
              multiline
              maxLength={500}
            />
          </Field>
        </View>

        {quote ? (
          <View style={{ marginTop: 6 }}>
            <Row label={t('cart.subtotal')} value={money(quote.subtotal_minor, quote.currency)} />
            {quote.delivery_fee_minor > 0 ? (
              <Row label={t('cart.delivery')} value={money(quote.delivery_fee_minor, quote.currency)} />
            ) : null}
            <Row
              label={t('cart.total')}
              value={(quote.requires_weighing ? `${t('cart.about')} ` : '') + money(quote.total_minor, quote.currency)}
              strong
            />
            {quote.requires_weighing ? (
              <View style={{ marginTop: 14 }}>
                <Note>
                  {t('shop.weighedNote')}{' '}
                  {t('cart.upTo', { amount: money(quote.weighed_ceiling_minor, quote.currency) })}
                </Note>
              </View>
            ) : null}
          </View>
        ) : null}

        {error ? <View style={{ marginTop: 16 }}><Note warn>{error}</Note></View> : null}

        <Button
          title={placing ? t('checkout.placing') : t('checkout.place')}
          onPress={place}
          disabled={!canPlace}
          busy={placing}
          style={{ marginTop: 22 }}
        />
      </ScrollView>
    </View>
  )
}

function isoDaysFromNow (days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

const s = StyleSheet.create({
  heading: { fontFamily: font.displaySemi, fontSize: 19, color: color.ink, marginBottom: 12 },
  option: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 12,
    backgroundColor: '#fff', borderWidth: 1, borderColor: color.line,
    borderRadius: space.radius, padding: 14, marginBottom: 10,
  },
  optionOn: { borderColor: color.forest, borderWidth: 2 },
  dot: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: color.line, marginTop: 2 },
  dotOn: { borderColor: color.forest, borderWidth: 6 },
  optionTitle: { fontFamily: font.semi, fontSize: 16, color: color.ink },
})

// app/src/views/Checkout.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useCart } from '../stores/cart'
import { useCatalogue } from '../stores/catalogue'
import { useAuth } from '../stores/auth'
import { api } from '../api/client'
import AppBar from '../components/AppBar.vue'
import { t, pick, money } from '../i18n'

const cart = useCart()
const catalogue = useCatalogue()
const auth = useAuth()
const router = useRouter()

const addresses = ref([])
const addressId = ref(null)
const date = ref('')
const payment = ref('cash')
const note = ref('')
const placing = ref(false)
const error = ref('')
const loading = ref(true)

/** The shop takes orders a day ahead, so today is not offered. */
const minDate = computed(() => {
  const lead = catalogue.delivery?.lead_days ?? 1
  const d = new Date()
  d.setDate(d.getDate() + lead)
  return d.toISOString().slice(0, 10)
})

const maxDate = computed(() => {
  const d = new Date()
  d.setDate(d.getDate() + 14)
  return d.toISOString().slice(0, 10)
})

const selected = computed(() => addresses.value.find((a) => a.id === addressId.value))
const quote = computed(() => cart.quote)

const canPlace = computed(() =>
  Boolean(addressId.value) &&
  Boolean(date.value) &&
  auth.profileComplete &&
  quote.value?.meets_minimum &&
  !placing.value
)

onMounted(async () => {
  try {
    const { data } = await api.addresses()
    addresses.value = data
    addressId.value = data.find((a) => a.is_default)?.id ?? data[0]?.id ?? null
    date.value = minDate.value

    // The fee depends on the zone, so the quote is refreshed once an address
    // is known — the basket screen priced it without one.
    if (selected.value) await cart.refreshQuote(selected.value.delivery_zone_id)
  } catch (e) {
    error.value = e.status === 0 ? t('err.offline') : t('err.generic')
  } finally {
    loading.value = false
  }
})

async function pickAddress (id) {
  addressId.value = id
  const zone = addresses.value.find((a) => a.id === id)?.delivery_zone_id ?? null
  try { await cart.refreshQuote(zone) } catch { /* totals stay as they were */ }
}

async function place () {
  if (!canPlace.value) return
  placing.value = true
  error.value = ''

  try {
    // Ids and quantities only. No prices leave this device.
    const order = await api.placeOrder({
      address_id: addressId.value,
      delivery_date: date.value,
      payment_method: payment.value,
      note: note.value.trim() || undefined,
      lines: cart.lines,
    })

    await cart.clear()
    router.replace({ name: 'order', params: { id: order.id }, query: { placed: '1' } })
  } catch (e) {
    if (e.payload?.unavailable_product_ids?.length) {
      await cart.dropUnavailable(e.payload.unavailable_product_ids)
      error.value = e.message
      await cart.refreshQuote()
    } else {
      const fields = e.fieldErrors ?? {}
      error.value = Object.values(fields)[0] ?? e.message ?? t('err.generic')
    }
  } finally {
    placing.value = false
  }
}
</script>

<template>
  <main class="screen">
    <AppBar :title="t('checkout.title')" back />

    <div v-if="loading" class="empty"><span class="spinner" style="margin:0 auto" /></div>

    <template v-else>
      <!-- A courier cannot deliver to a customer with no name and no phone;
           the server refuses the order too, so this is a shortcut rather than
           the control. -->
      <section v-if="!auth.profileComplete" class="wrap checkout__section">
        <p class="note note--warn">{{ t('profile.complete') }}</p>
        <RouterLink to="/profile" class="btn btn--ghost btn--block" style="margin-top:12px">
          {{ t('profile.title') }}
        </RouterLink>
      </section>

      <section class="wrap checkout__section">
        <h2 class="checkout__heading">{{ t('checkout.address') }}</h2>

        <div v-if="addresses.length" class="stack">
          <button
            v-for="a in addresses"
            :key="a.id"
            class="option"
            :class="{ 'is-on': addressId === a.id }"
            @click="pickAddress(a.id)"
          >
            <span class="option__dot" aria-hidden="true" />
            <span class="option__body">
              <strong v-if="a.label">{{ a.label }}</strong>
              <span>{{ a.line }}</span>
              <span v-if="a.notes" class="small muted">{{ a.notes }}</span>
            </span>
          </button>
        </div>

        <p v-else class="muted small">{{ t('address.none') }}</p>

        <RouterLink to="/profile/addresses" class="btn btn--ghost btn--block" style="margin-top:12px">
          {{ t('checkout.addAddress') }}
        </RouterLink>
      </section>

      <section class="wrap checkout__section">
        <h2 class="checkout__heading">{{ t('checkout.date') }}</h2>
        <input v-model="date" class="field__input" type="date" :min="minDate" :max="maxDate">
        <p class="field__hint">{{ t('checkout.dateNote') }}</p>
      </section>

      <section class="wrap checkout__section">
        <h2 class="checkout__heading">{{ t('checkout.payment') }}</h2>

        <div class="stack">
          <button class="option" :class="{ 'is-on': payment === 'cash' }" @click="payment = 'cash'">
            <span class="option__dot" aria-hidden="true" />
            <span class="option__body"><strong>{{ t('checkout.cash') }}</strong></span>
          </button>
          <button class="option" :class="{ 'is-on': payment === 'pos' }" @click="payment = 'pos'">
            <span class="option__dot" aria-hidden="true" />
            <span class="option__body"><strong>{{ t('checkout.pos') }}</strong></span>
          </button>
        </div>

        <p class="field__hint">{{ t('checkout.paymentNote') }}</p>
      </section>

      <section class="wrap checkout__section">
        <label class="field">
          <span class="field__label">{{ t('checkout.note') }}</span>
          <textarea v-model="note" class="field__input" rows="2" maxlength="500" />
        </label>
      </section>

      <section v-if="quote" class="wrap checkout__section">
        <div class="row">
          <span class="muted">{{ t('cart.subtotal') }}</span>
          <span>{{ money(quote.subtotal_minor, quote.currency) }}</span>
        </div>
        <div v-if="quote.delivery_fee_minor" class="row">
          <span class="muted">{{ t('cart.delivery') }}</span>
          <span>{{ money(quote.delivery_fee_minor, quote.currency) }}</span>
        </div>
        <div class="row">
          <span class="row__total">{{ t('cart.total') }}</span>
          <span class="row__total">
            <small v-if="quote.requires_weighing" class="muted checkout__about">{{ t('cart.about') }}</small>
            {{ money(quote.total_minor, quote.currency) }}
          </span>
        </div>

        <p v-if="quote.requires_weighing" class="note" style="margin-top:14px">
          {{ t('shop.weighedNote') }}
          <strong>{{ t('cart.upTo', { amount: money(quote.weighed_ceiling_minor, quote.currency) }) }}</strong>
        </p>
      </section>

      <p v-if="error" class="note note--warn wrap">{{ error }}</p>

      <div class="wrap checkout__cta">
        <button class="btn btn--primary btn--block" :disabled="!canPlace" @click="place">
          <span v-if="placing" class="spinner" />
          {{ placing ? t('checkout.placing') : t('checkout.place') }}
        </button>
      </div>
    </template>
  </main>
</template>

<style scoped>
.checkout__section{ padding-top:22px; }
.checkout__heading{ margin-bottom:12px; font-size:1.15rem; }
.checkout__about{ font-size:.78rem; font-weight:400; margin-right:4px; }
.checkout__cta{ padding:22px 0 28px; }

.option{
  display:flex; align-items:flex-start; gap:12px; width:100%;
  padding:14px;
  background:#fff; border:1px solid var(--line); border-radius:var(--radius);
  text-align:left;
}
.option.is-on{ border-color:var(--forest); box-shadow:inset 0 0 0 1px var(--forest); }
.option__dot{
  width:20px; height:20px; flex:none; margin-top:2px;
  border:2px solid var(--line); border-radius:50%;
}
.option.is-on .option__dot{
  border-color:var(--forest);
  background:radial-gradient(circle at center, var(--forest) 0 5px, transparent 6px);
}
.option__body{ display:flex; flex-direction:column; gap:2px; min-width:0; }
</style>
