// app/src/views/Orders.vue
<script setup>
import { ref, onMounted } from 'vue'
import { api } from '../api/client'
import AppBar from '../components/AppBar.vue'
import { t, money } from '../i18n'

const orders = ref([])
const loading = ref(true)
const error = ref('')

const LIVE = ['placed', 'confirmed', 'preparing', 'out_for_delivery']

onMounted(async () => {
  try {
    const { data } = await api.orders()
    orders.value = data
  } catch (e) {
    error.value = e.status === 0 ? t('err.offline') : t('err.generic')
  } finally {
    loading.value = false
  }
})

function pillClass (status) {
  if (LIVE.includes(status)) return 'pill pill--live'
  if (status === 'delivered') return 'pill pill--done'
  return 'pill pill--off'
}

function formatDate (iso) {
  if (!iso) return ''
  return new Date(iso).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })
}
</script>

<template>
  <main class="screen">
    <AppBar :title="t('orders.title')" />

    <div v-if="loading" class="empty"><span class="spinner" style="margin:0 auto" /></div>

    <p v-else-if="error" class="note note--warn wrap" style="margin-top:16px">{{ error }}</p>

    <div v-else-if="!orders.length" class="empty">
      <h3>{{ t('orders.empty') }}</h3>
      <RouterLink to="/shop" class="btn btn--ghost" style="margin-top:16px">
        {{ t('cart.browse') }}
      </RouterLink>
    </div>

    <section v-else class="wrap orders__list">
      <RouterLink
        v-for="o in orders"
        :key="o.id"
        :to="{ name: 'order', params: { id: o.id } }"
        class="order"
      >
        <div class="order__head">
          <strong class="order__code">{{ o.code }}</strong>
          <span :class="pillClass(o.status)">{{ t('status.' + o.status) }}</span>
        </div>

        <div class="order__meta small muted">
          {{ formatDate(o.delivery_date) }} · {{ o.items?.length ?? 0 }}
        </div>

        <div class="order__foot">
          <!-- Until the goods are weighed the figure is an estimate, and the
               screen says so rather than implying a precision we do not have. -->
          <small v-if="o.requires_weighing && !o.final_total_minor" class="muted">
            {{ t('cart.about') }}
          </small>
          <strong>{{ o.payable_display }}</strong>
        </div>
      </RouterLink>
    </section>
  </main>
</template>

<style scoped>
.orders__list{ padding-top:16px; display:flex; flex-direction:column; gap:11px; }
.order{
  display:block; padding:15px;
  background:#fff; border:1px solid var(--line-soft); border-radius:var(--radius);
  color:inherit; text-decoration:none;
}
.order__head{ display:flex; align-items:center; justify-content:space-between; gap:10px; }
.order__code{ font-family:var(--display); font-size:1.16rem; letter-spacing:.02em; }
.order__meta{ margin-top:5px; }
.order__foot{ display:flex; align-items:baseline; justify-content:flex-end; gap:5px; margin-top:11px; font-size:1.05rem; }
</style>

// app/app/(tabs)/orders.tsx
import { useCallback, useState } from 'react'
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native'
import { useFocusEffect, useRouter } from 'expo-router'

import { api, ApiError, type Order } from '@/lib/api'
import { useAuth } from '@/lib/auth'
import { t, useLang } from '@/lib/i18n'
import { AppBar, Button, Empty, Loading, Note, Small } from '@/components/ui'
import { color, font, space } from '@/theme/tokens'

const LIVE = ['placed', 'confirmed', 'preparing', 'out_for_delivery']

export default function Orders () {
  const auth = useAuth()
  const router = useRouter()
  useLang()

  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    if (!auth.signedIn) { setLoading(false); return }
    try {
      const { data } = await api.orders()
      setOrders(data)
      setError(null)
    } catch (e) {
      setError((e as ApiError).isOffline ? t('err.offline') : t('err.generic'))
    } finally {
      setLoading(false)
    }
  }, [auth.signedIn])

  // Refetch on focus: an order's status changes while the customer is looking
  // at another screen, and a stale list is the thing they came here to check.
  useFocusEffect(useCallback(() => { load() }, [load]))

  if (!auth.signedIn) {
    return (
      <View style={{ flex: 1 }}>
        <AppBar title={t('orders.title')} />
        <Empty title={t('auth.title')}>
          <Button title={t('auth.verify')} onPress={() => router.push('/sign-in')} style={{ marginTop: 16 }} />
        </Empty>
      </View>
    )
  }

  if (loading) return <View style={{ flex: 1 }}><AppBar title={t('orders.title')} /><Loading /></View>

  return (
    <View style={{ flex: 1 }}>
      <AppBar title={t('orders.title')} />

      <FlatList<Order>
        data={orders}
        keyExtractor={(o) => o.id}
        contentContainerStyle={{ padding: space.gutter, gap: 11 }}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={async () => { setRefreshing(true); await load(); setRefreshing(false) }}
            tintColor={color.forest}
          />
        }
        ListHeaderComponent={error ? <Note warn>{error}</Note> : null}
        ListEmptyComponent={
          <Empty title={t('orders.empty')}>
            <Button
              title={t('cart.browse')}
              variant="ghost"
              onPress={() => router.push('/(tabs)/shop')}
              style={{ marginTop: 16 }}
            />
          </Empty>
        }
        renderItem={({ item }) => (
          <Pressable
            onPress={() => router.push({ pathname: '/orders/[id]', params: { id: item.id } })}
            style={({ pressed }) => [s.card, pressed && { opacity: 0.9 }]}
          >
            <View style={s.head}>
              <Text style={s.code}>{item.code}</Text>
              <View style={[s.pill, pillStyle(item.status)]}>
                <Text style={[s.pillText, pillTextStyle(item.status)]}>{t(`status.${item.status}`)}</Text>
              </View>
            </View>

            <Small muted style={{ marginTop: 5 }}>
              {item.delivery_date ?? ''} · {item.items?.length ?? 0}
            </Small>

            <View style={s.foot}>
              {/* Until the goods are weighed the figure is an estimate, and the
                  screen says so rather than implying a precision we lack. */}
              {item.requires_weighing && item.final_total_minor === null ? (
                <Small muted>{t('cart.about')}</Small>
              ) : null}
              <Text style={s.total}>{item.payable_display}</Text>
            </View>
          </Pressable>
        )}
      />
    </View>
  )
}

function pillStyle (status: string) {
  if (LIVE.includes(status)) return { backgroundColor: color.forest }
  if (status === 'delivered') return { backgroundColor: color.leafXl }
  return { backgroundColor: color.paper3 }
}

function pillTextStyle (status: string) {
  if (LIVE.includes(status)) return { color: '#fff' }
  if (status === 'delivered') return { color: color.forest2 }
  return { color: color.ink3 }
}

const s = StyleSheet.create({
  card: {
    backgroundColor: '#fff', borderRadius: space.radius,
    borderWidth: StyleSheet.hairlineWidth, borderColor: color.lineSoft,
    padding: 15,
  },
  head: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  code: { fontFamily: font.displaySemi, fontSize: 19, letterSpacing: 0.4, color: color.ink },
  pill: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 999 },
  pillText: { fontFamily: font.semi, fontSize: 11 },
  foot: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'flex-end', gap: 5, marginTop: 11 },
  total: { fontFamily: font.bold, fontSize: 17, color: color.ink },
})
