// app/src/views/Profile.vue
<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../stores/auth'
import AppBar from '../components/AppBar.vue'
import { t, LANGS, currentLang, setLang } from '../i18n'

const auth = useAuth()
const router = useRouter()

const name = ref(auth.user?.name ?? '')
const phone = ref(auth.user?.phone ?? '')
const saving = ref(false)
const saved = ref(false)
const error = ref('')

// Two taps to delete an account, never one.
const confirmingDelete = ref(false)
const deleting = ref(false)

watch(() => auth.user, (u) => {
  name.value = u?.name ?? ''
  phone.value = u?.phone ?? ''
})

async function save () {
  saving.value = true
  saved.value = false
  error.value = ''

  try {
    await auth.updateProfile({ name: name.value.trim(), phone: phone.value.trim() })
    saved.value = true
    setTimeout(() => { saved.value = false }, 2400)
  } catch (e) {
    error.value = Object.values(e.fieldErrors ?? {})[0] ?? t('err.generic')
  } finally {
    saving.value = false
  }
}

async function changeLang (l) {
  await setLang(l)
  // Persisted on the account too, so the confirmation emails arrive in the
  // language the customer actually reads.
  if (auth.isSignedIn) {
    try { await auth.updateProfile({ locale: l }) } catch { /* local change stands */ }
  }
}

async function signOut () {
  await auth.signOut()
  router.replace('/shop')
}

async function deleteAccount () {
  deleting.value = true
  error.value = ''
  try {
    await auth.deleteAccount()
    router.replace('/shop')
  } catch (e) {
    // 409: an order is still in flight and somebody is about to deliver it.
    error.value = e.message ?? t('err.generic')
    confirmingDelete.value = false
  } finally {
    deleting.value = false
  }
}
</script>

<template>
  <main class="screen">
    <AppBar :title="t('profile.title')" />

    <div v-if="!auth.isSignedIn" class="empty">
      <h3>{{ t('auth.title') }}</h3>
      <RouterLink to="/sign-in" class="btn btn--primary" style="margin-top:16px">
        {{ t('auth.verify') }}
      </RouterLink>
    </div>

    <template v-else>
      <section class="wrap profile__section">
        <p v-if="!auth.profileComplete" class="note note--warn" style="margin-bottom:16px">
          {{ t('profile.complete') }}
        </p>

        <label class="field">
          <span class="field__label">{{ t('profile.name') }}</span>
          <input v-model="name" class="field__input" type="text" autocomplete="name" enterkeyhint="done">
        </label>

        <label class="field">
          <span class="field__label">{{ t('profile.phone') }}</span>
          <input
            v-model="phone"
            class="field__input"
            type="tel"
            inputmode="tel"
            autocomplete="tel"
            placeholder="+994 50 000 00 00"
          >
        </label>

        <p v-if="error" class="field__error">{{ error }}</p>

        <button class="btn btn--primary btn--block" :disabled="saving" @click="save">
          <span v-if="saving" class="spinner" />
          {{ saved ? t('profile.saved') : t('profile.save') }}
        </button>
      </section>

      <section class="wrap profile__section">
        <h2 class="profile__heading">{{ t('profile.language') }}</h2>
        <div class="profile__langs">
          <button
            v-for="l in LANGS"
            :key="l"
            class="chip"
            :class="{ 'is-on': currentLang === l }"
            @click="changeLang(l)"
          >{{ l.toUpperCase() }}</button>
        </div>
      </section>

      <section class="wrap profile__section">
        <RouterLink to="/profile/addresses" class="link-row">
          <span>{{ t('profile.addresses') }}</span>
          <span aria-hidden="true">→</span>
        </RouterLink>
      </section>

      <section class="wrap profile__section">
        <button class="btn btn--ghost btn--block" @click="signOut">{{ t('profile.logout') }}</button>
      </section>

      <!-- Apple Guideline 5.1.1(v): deleting the account must be possible from
           inside the app. It destroys the personal data rather than hiding it. -->
      <section class="wrap profile__section profile__danger">
        <template v-if="!confirmingDelete">
          <button class="profile__deletelink" @click="confirmingDelete = true">
            {{ t('profile.deleteAccount') }}
          </button>
        </template>

        <div v-else class="stack">
          <p class="note note--warn">{{ t('profile.deleteWarn') }}</p>
          <button class="btn btn--danger btn--block" :disabled="deleting" @click="deleteAccount">
            <span v-if="deleting" class="spinner" /> {{ t('profile.deleteConfirm') }}
          </button>
          <button class="btn btn--ghost btn--block" @click="confirmingDelete = false">{{ t('cancel') }}</button>
        </div>
      </section>
    </template>
  </main>
</template>

<style scoped>
.profile__section{ padding-top:22px; }
.profile__heading{ margin-bottom:11px; font-size:1.1rem; }
.profile__langs{ display:flex; gap:8px; }
.chip{
  padding:9px 17px;
  background:var(--paper-2); color:var(--ink-2);
  border-radius:999px; font-size:.85rem; font-weight:600;
}
.chip.is-on{ background:var(--forest); color:#fff; }

.link-row{
  display:flex; align-items:center; justify-content:space-between;
  padding:16px 15px;
  background:#fff; border:1px solid var(--line-soft); border-radius:var(--radius);
  color:inherit; text-decoration:none; font-weight:600;
}

.profile__danger{ padding-bottom:34px; }
.profile__deletelink{
  padding:10px 0;
  font-size:.9rem; color:var(--brick);
  text-decoration:underline; text-underline-offset:3px;
}
</style>

// app/app/(tabs)/profile.tsx
import { useEffect, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'

import { ApiError } from '@/lib/api'
import { useAuth } from '@/lib/auth'
import { LANGS, setLang, t, useLang, type Lang } from '@/lib/i18n'
import { AppBar, Body, Button, Empty, Field, Note, Small, inputStyle } from '@/components/ui'
import { color, font, space } from '@/theme/tokens'

export default function Profile () {
  const auth = useAuth()
  const router = useRouter()
  const lang = useLang()

  const [name, setName] = useState(auth.user?.name ?? '')
  const [phone, setPhone] = useState(auth.user?.phone ?? '')
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Two taps to delete an account, never one.
  const [confirmingDelete, setConfirmingDelete] = useState(false)
  const [deleting, setDeleting] = useState(false)

  useEffect(() => {
    setName(auth.user?.name ?? '')
    setPhone(auth.user?.phone ?? '')
  }, [auth.user])

  async function save () {
    setSaving(true); setSaved(false); setError(null)
    try {
      await auth.updateProfile({ name: name.trim(), phone: phone.trim() })
      setSaved(true)
      setTimeout(() => setSaved(false), 2400)
    } catch (e) {
      setError(Object.values((e as ApiError).fieldErrors)[0] ?? t('err.generic'))
    } finally {
      setSaving(false)
    }
  }

  async function changeLang (l: Lang) {
    await setLang(l)
    // Persisted on the account too, so sign-in emails arrive in the language
    // the customer actually reads.
    if (auth.signedIn) {
      try { await auth.updateProfile({ locale: l }) } catch { /* the local change stands */ }
    }
  }

  async function remove () {
    setDeleting(true); setError(null)
    try {
      await auth.deleteAccount()
      router.replace('/(tabs)/shop')
    } catch (e) {
      // 409: an order is in flight and someone is about to deliver it.
      setError((e as ApiError).message ?? t('err.generic'))
      setConfirmingDelete(false)
    } finally {
      setDeleting(false)
    }
  }

  if (!auth.signedIn) {
    return (
      <View style={{ flex: 1 }}>
        <AppBar title={t('profile.title')} />
        <Empty title={t('auth.title')}>
          <Button title={t('auth.verify')} onPress={() => router.push('/sign-in')} style={{ marginTop: 16 }} />
        </Empty>
      </View>
    )
  }

  return (
    <View style={{ flex: 1 }}>
      <AppBar title={t('profile.title')} />

      <ScrollView contentContainerStyle={{ padding: space.gutter, paddingBottom: 40 }}>
        {!auth.profileComplete ? (
          <View style={{ marginBottom: 18 }}><Note warn>{t('profile.complete')}</Note></View>
        ) : null}

        <Field label={t('profile.name')}>
          <TextInput
            style={inputStyle}
            value={name}
            onChangeText={setName}
            autoComplete="name"
            textContentType="name"
            returnKeyType="done"
          />
        </Field>

        <Field label={t('profile.phone')} error={error}>
          <TextInput
            style={inputStyle}
            value={phone}
            onChangeText={setPhone}
            placeholder="+994 50 000 00 00"
            placeholderTextColor={color.ink3}
            keyboardType="phone-pad"
            autoComplete="tel"
            textContentType="telephoneNumber"
          />
        </Field>

        <Button title={saved ? t('profile.saved') : t('profile.save')} onPress={save} busy={saving} />

        <Text style={s.heading}>{t('profile.language')}</Text>
        <View style={{ flexDirection: 'row', gap: 8 }}>
          {LANGS.map((l: Lang) => (
            <Pressable
              key={l}
              onPress={() => changeLang(l)}
              style={[s.chip, lang === l && { backgroundColor: color.forest }]}
            >
              <Text style={[s.chipText, lang === l && { color: '#fff' }]}>{l.toUpperCase()}</Text>
            </Pressable>
          ))}
        </View>

        <Pressable style={s.linkRow} onPress={() => router.push('/profile/addresses')}>
          <Text style={s.linkText}>{t('profile.addresses')}</Text>
          <Ionicons name="chevron-forward" size={20} color={color.ink3} />
        </Pressable>

        <Button
          title={t('profile.logout')}
          variant="ghost"
          onPress={async () => { await auth.signOut(); router.replace('/(tabs)/shop') }}
          style={{ marginTop: 22 }}
        />

        {/* Apple Guideline 5.1.1(v): deleting the account must be possible from
            inside the app. It destroys the personal data rather than hiding it. */}
        <View style={{ marginTop: 30 }}>
          {!confirmingDelete ? (
            <Pressable onPress={() => setConfirmingDelete(true)} style={{ paddingVertical: 10 }}>
              <Text style={s.deleteLink}>{t('profile.deleteAccount')}</Text>
            </Pressable>
          ) : (
            <View style={{ gap: 10 }}>
              <Note warn>{t('profile.deleteWarn')}</Note>
              <Button title={t('profile.deleteConfirm')} variant="danger" onPress={remove} busy={deleting} />
              <Button title={t('cancel')} variant="ghost" onPress={() => setConfirmingDelete(false)} />
            </View>
          )}
        </View>
      </ScrollView>
    </View>
  )
}

const s = StyleSheet.create({
  heading: { fontFamily: font.displaySemi, fontSize: 18, color: color.ink, marginTop: 26, marginBottom: 11 },
  chip: { paddingVertical: 9, paddingHorizontal: 17, borderRadius: 999, backgroundColor: color.paper2 },
  chipText: { fontFamily: font.semi, fontSize: 13, color: color.ink2 },
  linkRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#fff', borderWidth: StyleSheet.hairlineWidth, borderColor: color.lineSoft,
    borderRadius: space.radius, padding: 16, marginTop: 26,
  },
  linkText: { fontFamily: font.semi, fontSize: 16, color: color.ink },
  deleteLink: { fontFamily: font.body, fontSize: 15, color: color.brick, textDecorationLine: 'underline' },
})
