// app/src/views/Shop.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { useCatalogue } from '../stores/catalogue'
import { useCart } from '../stores/cart'
import ProductCard from '../components/ProductCard.vue'
import { t, pick, money } from '../i18n'

const catalogue = useCatalogue()
const cart = useCart()

const category = ref('all')
const query = ref('')
const loading = ref(false)

onMounted(async () => {
  if (!catalogue.loaded) loading.value = true
  try { await catalogue.load() } catch { /* the banner reports it */ }
  finally { loading.value = false }
})

const categories = computed(() => [
  { id: 'all', name: { az: t('shop.all'), ru: t('shop.all'), en: t('shop.all') } },
  ...catalogue.categories,
])

const results = computed(() => {
  let list = catalogue.inCategory(category.value)

  const q = query.value.trim().toLowerCase()
  if (q) {
    // Searches all three languages at once: a customer who knows a product as
    // "лосось" should find it with the app in Azerbaijani.
    list = list.filter((p) =>
      Object.values(p.name ?? {}).some((n) => String(n).toLowerCase().includes(q))
    )
  }

  return list
})

const showPopular = computed(() =>
  category.value === 'all' && !query.value.trim() && catalogue.popular.length > 0
)
</script>

<template>
  <main class="screen">
    <header class="topbar">
      <div class="topbar__in">
        <span class="topbar__title">{{ t('app.name') }}</span>
      </div>

      <div class="shop__search wrap">
        <input
          v-model="query"
          class="field__input"
          type="search"
          inputmode="search"
          autocapitalize="none"
          autocorrect="off"
          :placeholder="t('shop.search')"
        >
      </div>

      <div class="chips" role="tablist">
        <button
          v-for="c in categories"
          :key="c.id"
          class="chip"
          :class="{ 'is-on': category === c.id }"
          role="tab"
          :aria-selected="category === c.id"
          @click="category = c.id"
        >{{ pick(c.name) }}</button>
      </div>
    </header>

    <p v-if="catalogue.stale" class="note note--warn shop__stale wrap">
      {{ t('err.offline') }}
    </p>

    <div v-if="loading && !catalogue.loaded" class="empty">
      <span class="spinner" style="margin:0 auto" />
      <p style="margin-top:14px">{{ t('loading') }}</p>
    </div>

    <template v-else>
      <section v-if="showPopular" class="wrap shop__section">
        <h2 class="shop__heading">{{ t('shop.popular') }}</h2>
        <div class="grid">
          <ProductCard v-for="p in catalogue.popular" :key="p.id" :product="p" />
        </div>
      </section>

      <section class="wrap shop__section">
        <h2 v-if="showPopular" class="shop__heading">{{ t('shop.all') }}</h2>
        <div v-if="results.length" class="grid">
          <ProductCard v-for="p in results" :key="p.id" :product="p" />
        </div>
        <p v-else class="empty">{{ t('shop.empty') }}</p>
      </section>
    </template>

    <!-- A running total that follows the customer down the page, so they never
         have to open the basket to know where they are. -->
    <Transition name="sheet">
      <RouterLink v-if="!cart.isEmpty" to="/basket" class="shop__bar">
        <span class="shop__bar-count">{{ cart.count }}</span>
        <span>{{ t('cart.title') }}</span>
        <span class="shop__bar-go">→</span>
      </RouterLink>
    </Transition>
  </main>
</template>

<style scoped>
.shop__search{ padding-bottom:10px; }

.chips{
  display:flex; gap:8px;
  padding:0 var(--gutter) 12px;
  overflow-x:auto;
  scrollbar-width:none;
  /* Keeps the first and last chip off the screen edge while scrolling. */
  scroll-padding-inline:var(--gutter);
}
.chips::-webkit-scrollbar{ display:none; }
.chip{
  flex:none;
  padding:8px 15px;
  background:var(--paper-2); color:var(--ink-2);
  border-radius:999px;
  font-size:.85rem; font-weight:600; white-space:nowrap;
}
.chip.is-on{ background:var(--forest); color:#fff; }

.shop__stale{ margin:14px var(--gutter) 0; }
.shop__section{ padding-top:22px; }
.shop__heading{
  margin-bottom:13px;
  font-size:1.25rem;
}

.shop__bar{
  position:fixed; left:var(--gutter); right:var(--gutter);
  bottom:calc(var(--tabbar-h) + var(--safe-bottom) + 12px);
  z-index:25;
  display:flex; align-items:center; gap:11px;
  padding:14px 18px;
  background:var(--forest); color:#fff;
  border-radius:999px;
  font-weight:600; text-decoration:none;
  box-shadow:0 8px 24px rgba(27,41,22,.24);
}
.shop__bar-count{
  display:grid; place-items:center;
  min-width:24px; height:24px; padding:0 7px;
  background:var(--acid); color:var(--ink);
  border-radius:999px; font-size:.8rem; font-weight:700;
}
.shop__bar-go{ margin-left:auto; font-size:1.1rem; }
</style>

// app/app/(tabs)/shop.tsx
import { useMemo, useState } from 'react'
import { FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { useSafeAreaInsets } from 'react-native-safe-area-context'

import { useCatalogue } from '@/lib/catalogue'
import { useCart } from '@/lib/cart'
import { pick, t, useLang } from '@/lib/i18n'
import { ProductCard } from '@/components/ProductCard'
import { Empty, Loading, Note, Small, inputStyle } from '@/components/ui'
import type { Product } from '@/lib/api'
import { color, font, space } from '@/theme/tokens'

export default function Shop () {
  const catalogue = useCatalogue()
  const cart = useCart()
  const router = useRouter()
  const insets = useSafeAreaInsets()
  useLang()

  const [category, setCategory] = useState('all')
  const [query, setQuery] = useState('')
  const [refreshing, setRefreshing] = useState(false)

  const categories = useMemo(
    () => [{ id: 'all', name: { az: t('shop.all'), ru: t('shop.all'), en: t('shop.all') } }, ...catalogue.categories],
    [catalogue.categories]
  )

  const results = useMemo(() => {
    let list = catalogue.inCategory(category)
    const q = query.trim().toLowerCase()

    if (q) {
      // Searches all three languages at once: someone who knows a product as
      // "лосось" should find it with the app set to Azerbaijani.
      list = list.filter(p =>
        Object.values(p.name ?? {}).some(n => String(n).toLowerCase().includes(q))
      )
    }

    return list
  }, [catalogue, category, query])

  const showPopular = category === 'all' && !query.trim() && catalogue.popular.length > 0

  async function onRefresh () {
    setRefreshing(true)
    try { await catalogue.refresh() } catch { /* the stale banner reports it */ }
    finally { setRefreshing(false) }
  }

  if (!catalogue.loaded) return <Loading />

  return (
    <View style={{ flex: 1 }}>
      <View style={[s.header, { paddingTop: insets.top }]}>
        <View style={s.headerIn}>
          <Text style={s.title}>{t('app.name')}</Text>
        </View>

        <View style={{ paddingHorizontal: space.gutter, paddingBottom: 10 }}>
          <TextInput
            style={inputStyle}
            value={query}
            onChangeText={setQuery}
            placeholder={t('shop.search')}
            placeholderTextColor={color.ink3}
            autoCapitalize="none"
            autoCorrect={false}
            clearButtonMode="while-editing"
          />
        </View>

        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={s.chips}
        >
          {categories.map(c => (
            <Pressable
              key={c.id}
              onPress={() => setCategory(c.id)}
              accessibilityRole="tab"
              accessibilityState={{ selected: category === c.id }}
              style={[s.chip, category === c.id && { backgroundColor: color.forest }]}
            >
              <Text style={[s.chipText, category === c.id && { color: '#fff' }]}>{pick(c.name)}</Text>
            </Pressable>
          ))}
        </ScrollView>
      </View>

      <FlatList<Product>
        data={results}
        keyExtractor={(p) => p.id}
        numColumns={2}
        columnWrapperStyle={{ gap: 12 }}
        contentContainerStyle={[s.list, !cart.isEmpty && { paddingBottom: 92 }]}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={color.forest} />}
        ListHeaderComponent={
          <>
            {catalogue.stale ? (
              <View style={{ marginBottom: 14 }}><Note warn>{t('err.offline')}</Note></View>
            ) : null}

            {showPopular ? (
              <>
                <Text style={s.heading}>{t('shop.popular')}</Text>
                <View style={s.popularGrid}>
                  {catalogue.popular.map(p => (
                    <View key={p.id} style={{ width: '48%' }}><ProductCard product={p} /></View>
                  ))}
                </View>
                <Text style={s.heading}>{t('shop.all')}</Text>
              </>
            ) : null}
          </>
        }
        renderItem={({ item }) => <ProductCard product={item} />}
        ListEmptyComponent={<Empty title={t('shop.empty')} />}
        // Rendering 54 photo cards at once is what makes a shop screen stutter.
        initialNumToRender={8}
        windowSize={7}
        removeClippedSubviews
      />

      {/* A running total that follows the customer down the page, so they never
          have to open the basket to know where they are. */}
      {!cart.isEmpty ? (
        <Pressable
          onPress={() => router.push('/(tabs)/basket')}
          accessibilityRole="button"
          style={s.bar}
        >
          <View style={s.barCount}><Text style={s.barCountText}>{cart.count}</Text></View>
          <Text style={s.barText}>{t('cart.title')}</Text>
          <Text style={[s.barText, { marginLeft: 'auto' }]}>→</Text>
        </Pressable>
      ) : null}
    </View>
  )
}

const s = StyleSheet.create({
  header: {
    backgroundColor: color.paper,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.lineSoft,
  },
  headerIn: { minHeight: 52, justifyContent: 'center', paddingHorizontal: space.gutter },
  title: { fontFamily: font.displaySemi, fontSize: 22, color: color.ink },
  chips: { gap: 8, paddingHorizontal: space.gutter, paddingBottom: 12 },
  chip: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 999, backgroundColor: color.paper2 },
  chipText: { fontFamily: font.semi, fontSize: 13, color: color.ink2 },
  list: { padding: space.gutter, gap: 14, paddingBottom: 24 },
  heading: { fontFamily: font.displaySemi, fontSize: 20, color: color.ink, marginBottom: 12 },
  popularGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'space-between', marginBottom: 22 },
  bar: {
    position: 'absolute', left: space.gutter, right: space.gutter, bottom: 14,
    flexDirection: 'row', alignItems: 'center', gap: 11,
    backgroundColor: color.forest, borderRadius: 999,
    paddingVertical: 14, paddingHorizontal: 18,
    shadowColor: '#1B2916', shadowOpacity: 0.25, shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 }, elevation: 6,
  },
  barCount: {
    minWidth: 24, height: 24, paddingHorizontal: 7, borderRadius: 999,
    backgroundColor: color.acid, alignItems: 'center', justifyContent: 'center',
  },
  barCountText: { fontFamily: font.bold, fontSize: 12, color: color.ink },
  barText: { fontFamily: font.semi, fontSize: 15, color: '#fff' },
})
